### ISSUE TITLE
Question about pressure

### ISSUE THREAD

**Issue by Thomas-Bradford** [AguaClara/Dissolved-Gas#2]
@monroews 

Currently, the subteam's doing research to get a foundational understanding of fluidized beds, bubble formation, and gas solubility in water. There's one question we were wondering if you could clarify: 

Our planned apparatus involves utilizing the pressure gradient resulting from the height difference between ground-level and the reactor. While reading about a gas's solubility in relation to pressure (Henry's Law), it seems like the pressure in question is the gas's partial pressure in the space above a liquid.

Henry's Law: C=k * Pgas {Pgas -> partial pressure of a given gas above a liquid | C -> concentration of given gas in the liquid}

Pressure exerted by a fluid: P =fluid density density * g * h 

Are these pressures equivalent / interrelated? 

Thanks!

**Comment by monroews** [comment]
If you draw the reactor system you can calculate the pressure in the reactor. The pressure in the gas phase is the same as the pressure in the liquid phase except for the influence of surface tension. There doesn't have to be a nice horizontal water/gas interface for Henry's Law to apply.  Actually the Henry's law definition you found is incorrect because the interface pressure has nothing to do with the equilibrium deep in the reactor. An obvious example of this is the deep ocean!
